# Use official Node.js LTS Alpine image
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy only package files first to leverage Docker layer caching
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application code
COPY . .


COPY .env .env

# Ensure entrypoint script is executable
RUN chmod +x entrypoint.sh

# Build the application
RUN yarn build

# Expose application port
EXPOSE 3000

# Start the app
ENTRYPOINT ["sh", "./entrypoint.sh"]


